---
- name: Create Customization directory
  file:
    path: "{{ user_home }}/Customization"
    state: directory
  become_user: "{{ user }}"

- name: Create Workspace directory
  file:
    path: "{{ user_home }}/Workspace"
    state: directory
  become_user: "{{ user }}"

- name: Create Wallpapers directory
  file:
    path: "{{ user_home }}/Pictures/Wallpapers"
    state: directory
  become_user: "{{ user }}"
