---
- name: Symlink i3 config
  file:
    src: "{{ user_home }}/Customization/i3/i3"
    dest: "{{ user_home }}/.i3"
    state: link

- name: Symlink dunst
  file:
    src: "{{ user_home }}/Customization/i3/dunst"
    dest: "{{ user_home }}/.config/dunst"
    state: link

- name: Symlink Paper icons for status
  file:
    src: "{{ user_home }}/Customization/i3/icons/Paper"
    dest: "/usr/share/icons/Paper"
    state: link

- name: Symlink morc menu
  file:
    src: "{{ user_home }}/Customization/i3/morc_menu"
    dest: "{{ user_home }}/.config/morc_menu"
    state: link

- name: Install py3status
  pacman:
    name: py3status
    state: present
    update_cache: true
